// Punto de entrada del paquete compartido: tipos de base de datos (ver docs/06_estructura_de_datos.md)
// más la lógica de negocio, wiring de auth y componentes que usan las apps de Virikyna.

export * from './types/database'
export * from './lib/format'
export * from './lib/supabaseErrors'
export * from './lib/inventario'
export * from './lib/facturasCompra'
export * from './lib/devoluciones'
export * from './lib/arcaFacturacion'
export * from './lib/historialPrecio'
export * from './lib/perfiles'
export * from './lib/cargarImagen'
export * from './lib/numberInput'
export * from './lib/productoBusqueda'
export * from './lib/useDebouncedValue'
export * from './auth/createAuthController'
export * from './src/components/Footer'
export * from './src/components/VentasDelDiaTab'
export * from './src/components/BottomSheet'
export * from './src/components/StockBajoCard'
export * from './src/components/DefectuososCard'
export * from './src/components/ScanButton'
export * from './src/components/ProductoBuscador'
export * from './src/components/CodigoBarrasBox'
// Primitivos de UI de escritorio (Local y Gestión) — virikyna-inventario usa BottomSheet y los suyos.
export * from './src/components/Modal'
export * from './src/components/ConfirmDialog'
export * from './src/components/FormField'
export { CargarFacturaCompraModal } from './src/components/CargarFacturaCompraModal'
export * from './src/components/DropdownFlotante'
export type { CrearProductoRender, ProductoCreadoFactura } from './src/components/ItemFacturaRow'
